name: Publish Demo
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: amondnet/vercel-action@v19
      with:
        working-directory: 'packages/demo'
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-args: '--prod' #Optional
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}  #Required
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}} #Required 